spring.profiles.active=simulator

# Aplicación
app.name=Smart Elevator
app.version=1.0.0

# Logging
logging.level.root=INFO
logging.level.co.edu.unillanos.elevator=DEBUG
logging.pattern.console=%d{yyyy-MM-dd HH:mm:ss} - %logger{36} - %msg%n

# SERVER CONFIG - REST API
server.port=8080
server.servlet.context-path=/
spring.webflux.max-in-memory-buffer-size=1MB

# API Documentation
springdoc.api-docs.path=/api-docs
springdoc.swagger-ui.path=/swagger-ui.html

# SSE CONFIG
spring.mvc.async.request-timeout=60000
server.tomcat.threads.max=200
server.tomcat.threads.min-spare=10

# Elevator specific configs
elevator.api.version=v1
elevator.default-travel-time-per-floor=1000
